version: "3.3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "fivecity_live"
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8123:3000"
