version: "3.3"

services:
  app:
    image: "ghcr.io/gorlikitsme/fivecity-transmisje-live:latest"
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: "fivecity_live"
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8123:3000"
