name: Run All Tests
on:
  push:
  pull_request:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: yarn

      - name: Lint
        run: yarn lint

      # Wyłączone bo /pages/build_json_files.tsx
      # - name: Build
      #   run: yarn build